# Generated by Django 6.0.5 on 2026-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100, null=True)),
                ('device_id', models.CharField(max_length=100)),
                ('sensor', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20, null=True)),
                ('ts_ms', models.BigIntegerField()),
                ('seq', models.IntegerField(null=True)),
                ('topic', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'measurements',
                'indexes': [models.Index(fields=['device_id'], name='measurement_device__fc66f4_idx'), models.Index(fields=['sensor'], name='measurement_sensor_f1906e_idx'), models.Index(fields=['ts_ms'], name='measurement_ts_ms_d721a6_idx')],
            },
        ),
    ]
